# Generated by Django 4.2.17 on 2025-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(
                        db_index=True, unique=True, verbose_name="ID операции"
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="Сумма")),
                (
                    "payer_inn",
                    models.CharField(max_length=12, verbose_name="ИНН плательщика"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=32, verbose_name="Номер документа"),
                ),
                ("document_date", models.DateTimeField(verbose_name="Дата документа")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
