# Generated by Django 4.2.17 on 2025-05-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        db_index=True, max_length=12, unique=True, verbose_name="ИНН"
                    ),
                ),
                ("balance", models.BigIntegerField(default=0, verbose_name="Баланс")),
            ],
        ),
        migrations.CreateModel(
            name="BalanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="Сумма изменения")),
                ("operation_id", models.UUIDField(verbose_name="ID операции")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
